### ISSUE TITLE
All Rainbows splitting is incorrect

### ISSUE THREAD

**Issue by badBlackShark** [Voxelse/ASLScripts#5]
This presumably applies to the All Levels splitter as well.

When running All Rainbows, the Spooky Times and Night Crisis batch split after completing Tricks & Treats / Pinball respectively. However, due to needing to beat Kentony / Kentinator respectively in those batches to progress in the game, those splits are one map too early.

**Comment by badBlackShark** [comment]
This is for the "batches" method of splitting. I assume the "levels" version works as intended.

**Comment by Voxelse** [comment]
Hmm actually that's pretty weird, I just tested, and for me, it works fine for All Rainbows.
However and for whatever reason, I forgot to add the Kentony/Kentinator constraint for All Levels so yeah it will split earlier for All Levels but it should split well for All Rainbows.
I don't do a "true" check for All Rainbows though, I only check if a medal is earned instead of looking if the four are earned which simplify the checks and shouldn't affect the run since I don't think people would do a level with only gold or less, quit do other levels and go back to do rainbow on it but maybe I'm wrong.

I've fixed it for All Levels and added the proper medal check for All Rainbows/100% just in case, but it shouldn't fix the problem for All Rainbows as it should be working already.
